### ISSUE TITLE
i'm getting errors for building the java-demo-app on Jenkins 

### ISSUE THREAD

**Issue by SubhajitDutta07** [dhgautam/demoapp-freestyle-template#1]
23:35:25 Started by user [Subhajit Dutta ](http://localhost:8080/user/subhajit)
23:35:25 Running as SYSTEM
23:35:25 Building in workspace /var/jenkins_home/workspace/java-app
23:35:25 The recommended git tool is: NONE
23:35:26 using credential Subhajit
23:35:26  > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/java-app/.git # timeout=10
23:35:26 Fetching changes from the remote Git repository
23:35:26  > git config remote.origin.url git@github.com:SubhajitDutta07/demo-app-freestyle.git # timeout=10
23:35:26 Fetching upstream changes from git@github.com:SubhajitDutta07/demo-app-freestyle.git
23:35:26  > git --version # timeout=10
23:35:26  > git --version # 'git version 2.39.2'
23:35:26 using GIT_SSH to set credentials 
23:35:26 Verifying host key using known hosts file
23:35:26  > git fetch --tags --force --progress -- git@github.com:SubhajitDutta07/demo-app-freestyle.git +refs/heads/*:refs/remotes/origin/* # timeout=10
23:35:29  > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
23:35:29 Checking out Revision 0db5a93a6775203af7d5bc128f79fee1a9752b35 (refs/remotes/origin/master)
23:35:29  > git config core.sparsecheckout # timeout=10
23:35:29  > git checkout -f 0db5a93a6775203af7d5bc128f79fee1a9752b35 # timeout=10
23:35:29 Commit message: "Initial commit"
23:35:29  > git rev-list --no-walk 0db5a93a6775203af7d5bc128f79fee1a9752b35 # timeout=10
23:35:29 [java-app] $ /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/maven3/bin/mvn -f java-demo-app/pom.xml clean verify site
23:35:29 [INFO] Scanning for projects...
23:35:29 [INFO] 
23:35:29 [INFO] -----------------< com.hgautam.examples:java-demo-app >-----------------
23:35:29 [INFO] Building java-demo-app 1.0-SNAPSHOT
23:35:29 [INFO]   from pom.xml
23:35:29 [INFO] --------------------------------[ jar ]---------------------------------
23:35:29 [INFO] 
23:35:29 [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ java-demo-app ---
23:35:29 [INFO] Deleting /var/jenkins_home/workspace/java-app/java-demo-app/target
23:35:29 [INFO] 
23:35:29 [INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ java-demo-app ---
23:35:29 [INFO] argLine set to -javaagent:/var/jenkins_home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/var/jenkins_home/workspace/java-app/java-demo-app/target/jacoco.exec
23:35:29 [INFO] 
23:35:29 [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ java-demo-app ---
23:35:29 [INFO] Using 'UTF-8' encoding to copy filtered resources.
23:35:29 [INFO] skip non existing resourceDirectory /var/jenkins_home/workspace/java-app/java-demo-app/src/main/resources
23:35:29 [INFO] 
23:35:29 [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ java-demo-app ---
23:35:29 [INFO] Changes detected - recompiling the module!
23:35:29 [INFO] Compiling 2 source files to /var/jenkins_home/workspace/java-app/java-demo-app/target/classes
23:35:30 [INFO] 
23:35:30 [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ java-demo-app ---
23:35:30 [INFO] Using 'UTF-8' encoding to copy filtered resources.
23:35:30 [INFO] skip non existing resourceDirectory /var/jenkins_home/workspace/java-app/java-demo-app/src/test/resources
23:35:30 [INFO] 
23:35:30 [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ java-demo-app ---
23:35:30 [INFO] Changes detected - recompiling the module!
23:35:30 [INFO] Compiling 1 source file to /var/jenkins_home/workspace/java-app/java-demo-app/target/test-classes
23:35:30 [INFO] 
23:35:30 [INFO] --- maven-surefire-plugin:3.0.0-M1:test (default-test) @ java-demo-app ---
23:35:30 [INFO] 
23:35:30 [INFO] -------------------------------------------------------
23:35:30 [INFO]  T E S T S
23:35:30 [INFO] -------------------------------------------------------
23:35:30 [WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire-reports/2024-03-08T18-05-30_148-jvmRun1.dumpstream
23:35:30 [INFO] 
23:35:30 [INFO] Results:
23:35:30 [INFO] 
23:35:30 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
23:35:30 [INFO] 
23:35:30 [INFO] ------------------------------------------------------------------------
23:35:30 [INFO] BUILD FAILURE
23:35:30 [INFO] ------------------------------------------------------------------------
23:35:30 [INFO] Total time:  0.748 s
23:35:30 [INFO] Finished at: 2024-03-08T18:05:30Z
23:35:30 [INFO] ------------------------------------------------------------------------
23:35:30 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project java-demo-app: There are test failures.
23:35:30 [ERROR] 
23:35:30 [ERROR] Please refer to /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire-reports for the individual test results.
23:35:30 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
23:35:30 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:35:30 [ERROR] Command was /bin/sh -c cd /var/jenkins_home/workspace/java-app/java-demo-app && /opt/java/openjdk/bin/java -javaagent:/var/jenkins_home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/var/jenkins_home/workspace/java-app/java-demo-app/target/jacoco.exec -jar /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire/surefirebooter16987599871826940720.jar /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire 2024-03-08T18-05-30_148-jvmRun1 surefire13286891634232942308tmp surefire_06006634755437264150tmp
23:35:30 [ERROR] Error occurred in starting fork, check output in log
23:35:30 [ERROR] Process Exit Code: 134
23:35:30 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:35:30 [ERROR] Command was /bin/sh -c cd /var/jenkins_home/workspace/java-app/java-demo-app && /opt/java/openjdk/bin/java -javaagent:/var/jenkins_home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/var/jenkins_home/workspace/java-app/java-demo-app/target/jacoco.exec -jar /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire/surefirebooter16987599871826940720.jar /var/jenkins_home/workspace/java-app/java-demo-app/target/surefire 2024-03-08T18-05-30_148-jvmRun1 surefire13286891634232942308tmp surefire_06006634755437264150tmp
23:35:30 [ERROR] Error occurred in starting fork, check output in log
23:35:30 [ERROR] Process Exit Code: 134
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:991)
23:35:30 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:837)
23:35:30 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
23:35:30 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
23:35:30 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:299)
23:35:30 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
23:35:30 [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
23:35:30 [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
23:35:30 [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
23:35:30 [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
23:35:30 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:35:30 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
23:35:30 [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
23:35:30 [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
23:35:30 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
23:35:30 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
23:35:30 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
23:35:30 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
23:35:30 [ERROR] 
23:35:30 [ERROR] -> [Help 1]
23:35:30 [ERROR] 
23:35:30 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
23:35:30 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
23:35:30 [ERROR] 
23:35:30 [ERROR] For more information about the errors and possible solutions, please read the following articles:
23:35:30 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
23:35:30 Build step 'Invoke top-level Maven targets' marked build as failure
23:35:30 Archiving artifacts
23:35:30 [SpotBugsPMD] Skipping execution of recorder since overall result is 'FAILURE'
23:35:30 Sending e-mails to: subhajitdutta99907@gmail.com
23:35:30 ERROR: Couldn't connect to host, port: localhost, 25; timeout 60000
23:35:30 org.eclipse.angus.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout 60000;
23:35:30   nested exception is:
23:35:30 	java.net.ConnectException: Connection refused
23:35:30 	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2243)
23:35:30 	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:729)
23:35:30 	at jakarta.mail.Service.connect(Service.java:345)
23:35:30 	at jakarta.mail.Service.connect(Service.java:225)
23:35:30 	at jakarta.mail.Service.connect(Service.java:174)
23:35:30 	at jakarta.mail.Transport.send0(Transport.java:232)
23:35:30 	at jakarta.mail.Transport.send(Transport.java:102)
23:35:30 	at hudson.tasks.MailSender.run(MailSender.java:131)
23:35:30 	at hudson.tasks.Mailer.perform(Mailer.java:175)
23:35:30 	at hudson.tasks.Mailer.perform(Mailer.java:138)
23:35:30 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
23:35:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
23:35:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
23:35:30 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
23:35:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
23:35:30 	at hudson.model.Run.execute(Run.java:1916)
23:35:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
23:35:30 	at hudson.model.ResourceController.execute(ResourceController.java:101)
23:35:30 	at hudson.model.Executor.run(Executor.java:442)
23:35:30 Caused by: java.net.ConnectException: Connection refused
23:35:30 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
23:35:30 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
23:35:30 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
23:35:30 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
23:35:30 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
23:35:30 	at java.base/java.net.Socket.connect(Unknown Source)
23:35:30 	at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:366)
23:35:30 	at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:243)
23:35:30 	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2193)
23:35:30 	... 18 more
23:35:30 Finished: FAILURE

The above contains the console output, would you be able to help me out, i was leaning Jenkins from your course on edx.

**Comment by SubhajitDutta07** [comment]
The first thing that i can see on the Jenkins UI is that in the post build actions that the file **/target/*.jar  "**/target" doesn't exits. I have been using the jenkins through Docker container.

**Comment by PrometheRus** [comment]
I have the same problem if I use **openjdk-21**
```
10:10:33 [ERROR] Command was /bin/sh -c cd /var/lib/jenkins/workspace/demo/java-demo-app && /usr/lib/jvm/java-21-openjdk-21.0.5.0.10-3.el9.alma.1.x86_64/bin/java -javaagent:/var/lib/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/var/lib/jenkins/workspace/demo/java-demo-app/target/jacoco.exec -jar /var/lib/jenkins/workspace/demo/java-demo-app/target/surefire/surefirebooter16465767388525052297.jar /var/lib/jenkins/workspace/demo/java-demo-app/target/surefire 2024-11-03T10-10-33_158-jvmRun1 surefire9146330482704722280tmp surefire_02076945543386133859tmp
```

```
[root@jenkins demo]# /bin/sh -c cd /var/lib/jenkins/workspace/demo/java-demo-app && /usr/lib/jvm/java-21-openjdk-21.0.5.0.10-3.el9.alma.1.x86_64/bin/java -javaagent:/var/lib/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/var/lib/jenkins/workspace/demo/java-demo-app/target/jacoco.exec -jar /var/lib/jenkins/workspace/demo/java-demo-app/target/surefire/surefirebooter16465767388525052297.jar /var/lib/jenkins/workspace/demo/java-demo-app/target/surefire 2024-11-03T10-10-33_158-jvmRun1 surefire9146330482704722280tmp surefire_02076945543386133859tmp
Error: Unable to access jarfile /var/lib/jenkins/workspace/demo/java-demo-app/target/surefire/surefirebooter16465767388525052297.jar
```

But if I use **openjdk-11** (as stated in the 'Requirements' section) everything is fine. 

> The java-app job requires Java version 11
